### ISSUE TITLE
Error: Couldn't get 'time_to_live'

### ISSUE THREAD

**Issue by zach-b** [Azure/azure-uamqp-python#24]
After updating from 0.1.0.rc1 to 0.1.0 I get the following error when receiving any message from the azure service bus

> Traceback (most recent call last):
>   File "/[...]/lib/python3.6/site-packages/uamqp/receiver.py", line 235, in _message_received
>     settler=settler)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 92, in __init__
>     self._parse_message(message)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 142, in _parse_message
>     self.header = MessageHeader(header=_header)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 958, in __init__
>     self.time_to_live = header.time_to_live
>   File "./src/header.pyx", line 78, in uamqp.c_uamqp.cHeader.time_to_live.__get__
>   File "./src/base.pyx", line 31, in uamqp.c_uamqp.StructBase._value_error
> ValueError: Operation failed.
> Error: Couldn't get 'time_to_live'.
> Exception ignored in: 'uamqp.c_uamqp.on_message_received'
> Traceback (most recent call last):
>   File "/[...]/lib/python3.6/site-packages/uamqp/receiver.py", line 235, in _message_received
>     settler=settler)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 92, in __init__
>     self._parse_message(message)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 142, in _parse_message
>     self.header = MessageHeader(header=_header)
>   File "/[...]/lib/python3.6/site-packages/uamqp/message.py", line 958, in __init__
>     self.time_to_live = header.time_to_live
>   File "./src/header.pyx", line 78, in uamqp.c_uamqp.cHeader.time_to_live.__get__
>   File "./src/base.pyx", line 31, in uamqp.c_uamqp.StructBase._value_error
> ValueError: Operation failed.
> Error: Couldn't get 'time_to_live'.
> 
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

When commenting line 958 (`self.time_to_live = header.time_to_live`) of uamqp/message.py the error disappears, it seems that there is a problem with the code loading the time_to_live from the header (no default value or something?)

**Comment by annatisch** [comment]
Good catch - I will take a look! Thanks for the report :)

**Comment by annatisch** [comment]
Hi @zach-b - I've just run some tests against a ServiceBus queue and I'm not seeing this error.
What kind of SB entity are you receiving from? What is the message ttl for this entity configured to?

It's likely that we're raising a ValueError instead of just returning None when the header doesn't have the ttl value set - though I'm unsure why SB wouldn't be setting this value on the header.

**Comment by zach-b** [comment]
Hi annatisch, I checked the ttl and turns out I left it to the default when creating a queue through the REST interface, which is actually huge (see https://docs.microsoft.com/en-us/rest/api/servicebus/queues/createorupdate): a bit more than 10675199 days.
Setting it to a more reasonable value made the bug go away.

It seems that the bug occurs when the ttl is too high
